servers:
  hosts:
    Client:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_private_key_file: /root/OTUS/Kazay/Backups/.vagrant/machines/Client/virtualbox/private_key
    BackUp:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_private_key_file: /root/OTUS/Kazay/Backups/.vagrant/machines/BackUp/virtualbox/private_key

